name: Build projects
description: Build projects

inputs:
  package_manager:
    description: The package manager to use (npm, yarn, pnpm)
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Project
      uses: ./.github/workflows/utils/node-setup
      with:
        package_manager: ${{inputs.package_manager}}

    - name: Build
      shell: bash
      run: ${PACKAGE_MANAGER} build
