name: Build projects PNPM
description: Build projects PNPM

runs:
  using: "composite"
  steps:
    - name: Install PNPM
      uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: false
        cache: "pnpm"

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Get pnpm path
      shell: bash
      run: |
        echo "pnpmPath=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: "${{ env.pnpmPath }}"
        key: ${{ hashFiles('**/pnpm-lock.yaml') }}-${{ env.envHash }}-${{ env.os }}-pnpm-store

    - name: Install dependencies
      shell: bash
      run: pnpm i

    - name: Determine package manager
      shell: bash
      run: echo "PACKAGE_MANAGER=pnpm" >> $GITHUB_ENV
