name: CI

on:
  pull_request:
    branches: [main, staging, develop]

env:
  PACKAGE_MANAGER: pnpm # npm | pnpm | yarn

jobs:
  pull_request_checks:
    runs-on: ubuntu-latest
    name: "Pull Request Checks"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull Request Check
        uses: ./.github/workflows/modules/pull-request-convention

  building:
    runs-on: ubuntu-latest
    name: "Build Projects"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build projects
        uses: ./.github/workflows/modules/build-projects
        with:
          package_manager: ${{env.PACKAGE_MANAGER}}

  linting:
    runs-on: ubuntu-latest
    name: "Lint projects"
    permissions:
      contents: write
    needs:
      - pull_request_checks
      - building
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Linting
        uses: ./.github/workflows/modules/lint
        with:
          package_manager: ${{env.PACKAGE_MANAGER}}

      - name: Auto Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        if: github.base_ref == 'develop'
        with:
          file_pattern: '*.ts *.tsx'
          commit_message: 'fix: Prettier/Eslint'
